// <auto-generated />
using System;
using BankLocker.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BankLocker.Migrations
{
    [DbContext(typeof(BankLockerContext))]
    [Migration("20190225144148_locker-final")]
    partial class lockerfinal
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BankLocker.Models.LocationBank", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedOn");

                    b.Property<int>("LocationId");

                    b.Property<int?>("LocationModelId");

                    b.Property<DateTime>("ModifiedOn");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("LocationModelId");

                    b.ToTable("LocationBank");
                });

            modelBuilder.Entity("BankLocker.Models.LocationModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedOn");

                    b.Property<DateTime>("ModifiedOn");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Location");
                });

            modelBuilder.Entity("BankLocker.Models.LockerModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("LocationBankId");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("LocationBankId");

                    b.ToTable("Locker");
                });

            modelBuilder.Entity("BankLocker.Models.LocationBank", b =>
                {
                    b.HasOne("BankLocker.Models.LocationModel")
                        .WithMany("LocationBanks")
                        .HasForeignKey("LocationModelId");
                });

            modelBuilder.Entity("BankLocker.Models.LockerModel", b =>
                {
                    b.HasOne("BankLocker.Models.LocationBank")
                        .WithMany("Lockers")
                        .HasForeignKey("LocationBankId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
